/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_lpuart.h"
#include "fsl_clock.h"
#include "fsl_pwm.h"
#include "fsl_ctimer.h"
#include "fsl_lpadc.h"
#include "fsl_lpi2c.h"
#include "fsl_lpspi.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* BOARD_InitPeripherals defines for SysTick */
/* Definition of clock source frequency. */
#define SYSTICK_CLK_FREQ 12000000UL
/* Definition of clock source frequency. */
#define SYSTICK_TICKS 120000UL
/* SysTick interrupt vector ID (number). */
#define SYSTICK_TIMER_REFERENCE_IRQN SysTick_IRQn
/* SysTick interrupt handler identifier. */
#define SysTick_Handler SysTick_Handler
/* Definition of peripheral ID */
#define LPUART0_PERIPHERAL LPUART0
/* Definition of the clock source frequency */
#define LPUART0_CLOCK_SOURCE 48000000UL
/* Definition of peripheral ID */
#define FLEXPWM0_PERIPHERAL FLEXPWM0
/* Definition of submodule 0 ID */
#define FLEXPWM0_SM0 kPWM_Module_0
/* Definition of clock source of submodule 0 frequency in Hertz */
#define FLEXPWM0_SM0_SM_CLK_SOURCE_FREQ_HZ 12000000U
/* Definition of submodule 0 counter clock source frequency in Hertz - FLEXPWM0_SM0_SM_CLK_SOURCE_FREQ_HZ divided by prescaler */
#define FLEXPWM0_SM0_COUNTER_CLK_SOURCE_FREQ_HZ 12000000U
/* Definition of submodule 0 counter (PWM) frequency in Hertz */
#define FLEXPWM0_SM0_COUNTER_FREQ_HZ 1000U
/* Definition of submodule 0 channel A ID */
#define FLEXPWM0_SM0_A kPWM_PwmA
/* Definition of submodule 0 channel B ID */
#define FLEXPWM0_SM0_B kPWM_PwmB
/* Definition of submodule 0 channel X ID */
#define FLEXPWM0_SM0_X kPWM_PwmX
/* Definition of fault Fault0 ID */
#define FLEXPWM0_F0_FAULT0 kPWM_Fault_0
/* Definition of fault Fault1 ID */
#define FLEXPWM0_F0_FAULT1 kPWM_Fault_1
/* Definition of fault Fault2 ID */
#define FLEXPWM0_F0_FAULT2 kPWM_Fault_2
/* Definition of fault Fault3 ID */
#define FLEXPWM0_F0_FAULT3 kPWM_Fault_3
/* Definition of peripheral ID */
#define CTIMER0_PERIPHERAL CTIMER0
/* Timer tick frequency in Hz (input frequency of the timer) */
#define CTIMER0_TICK_FREQ 1UL
/* Timer tick period in ns (input period of the timer) */
#define CTIMER0_TICK_PERIOD 1000000000UL
/* Definition of PWM period channel. */
#define CTIMER0_PWM_PERIOD_CH kCTIMER_Match_0
/* Definition of channel 0 ID */
#define CTIMER0_MATCH_0_CHANNEL kCTIMER_Match_0
/* CTIMER0 interrupt vector ID (number). */
#define CTIMER0_TIMER_IRQN CTIMER0_IRQn
/* Alias for ADC0 peripheral */
#define ADC0_PERIPHERAL ADC0
/* BOARD_InitPeripherals defines for LPI2C0 */
/* Definition of peripheral ID */
#define LPI2C0_PERIPHERAL LPI2C0
/* Definition of clock source */
#define LPI2C0_CLOCK_FREQ 12000000UL
/* Transfer buffer size */
#define LPI2C0_MASTER_BUFFER_SIZE 1
/* Definition of follower address */
#define LPI2C0_MASTER_SLAVE_ADDRESS 0
/* BOARD_InitPeripherals defines for LPSPI0 */
/* Definition of peripheral ID */
#define LPSPI0_PERIPHERAL LPSPI0
/* Definition of clock source */
#define LPSPI0_CLOCK_FREQ 48000000UL

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const lpuart_config_t LPUART0_config;
extern pwm_config_t FLEXPWM0_SM0_config;

extern pwm_signal_param_t FLEXPWM0_SM0_pwm_function_config[1];
extern const pwm_fault_input_filter_param_t FLEXPWM0_faultInputFilter_config;
extern const pwm_fault_param_t FLEXPWM0_Fault0_fault_config;
extern const pwm_fault_param_t FLEXPWM0_Fault1_fault_config;
extern const pwm_fault_param_t FLEXPWM0_Fault2_fault_config;
extern const pwm_fault_param_t FLEXPWM0_Fault3_fault_config;
extern const ctimer_config_t CTIMER0_config;
extern const ctimer_match_config_t CTIMER0_Match_0_config;
extern const lpadc_config_t ADC0_config;
extern const lpi2c_master_config_t LPI2C0_masterConfig;
extern lpi2c_master_transfer_t LPI2C0_masterTransfer;
extern uint8_t LPI2C0_masterBuffer[LPI2C0_MASTER_BUFFER_SIZE];
extern lpi2c_master_handle_t LPI2C0_masterHandle;
extern const lpspi_master_config_t LPSPI0_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
